version: '2'
services:

  rails-app:
    build:
      context: .
      args:
          RAILS_ENV: ${RAILS_ENV}
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      TAPP: ${TAPP}
      EMAIL_TYPE: ${EMAIL_TYPE}
      EMAIL_USER: ${EMAIL_USER}
      TA_COORD: ${TA_COORD}
      CUPE_SITE: ${CUPE_SITE}
      RECIPIENT: ${RECIPIENT}
    networks:
      - default
      - tapp_frontend
    ports:
      - "5000:5000"
    links:
      - postgres
    external_links:
      - tapp_rails-app:tapp
    command: >
      ./bin/rails-server-entrypoint -b 0.0.0.0 -p 5000 -P /dev/null

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data

networks:
  tapp_frontend:
    external: true
