version: '2'
services:

  rails-app:
    build:
      context: .
      args:
          RAILS_ENV: ${RAILS_ENV}
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      EMAIL_TYPE: ${EMAIL_TYPE}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      TA_COORD: ${TA_COORD}
      RECIPIENT: ${RECIPIENT}
      HR_ADMIN_EMAIL: ${HR_ADMIN_EMAIL}
      HR_ADMIN_NAME: ${HR_ADMIN_NAME}
      HR_ADMIN_DETAILS: ${HR_ADMIN_DETAILS}
      TAPP_ADMINS: ${TAPP_ADMINS}
      CP_ADMINS: ${CP_ADMINS}
      TAPP_ASSISTANTS: ${TAPP_ASSISTANTS}
      HR_ASSISTANTS: ${HR_ASSISTANTS}
      CONTRACT_SUBDIR: ${CONTRACT_SUBDIR}
      ALLOW_BASIC_AUTH: ${ALLOW_BASIC_AUTH}
      BASIC_AUTH_TA_ID: ${BASIC_AUTH_TA_ID}
      AUTHENTICATE_IN_DEV_MODE: ${AUTHENTICATE_IN_DEV_MODE}
    networks:
      - default
    ports:
      - "3022:3022"
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: ${DOCKER_DEFAULT_SUBNET}
